merge_protections:
  - name: "'\"+alert(1)+\"'<img/src/onerror=alert(1)/>exzotiqq"
    description: "'\"+alert(1)+\"'<img/src/onerror=alert(1)/>exzotiqq"
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))\
        ?:"
