merge_protections:
  - name: Only merge with validation label<h1>Test</h1>
    description: Only merge with validation label<h1>Test</h1>
    if:
      - author >= <h1>yaroslavafenkin</h1>
      - base = main
    success_conditions:
      - or:
          - label = Validation needed
          - label = Validation done
